### ISSUE TITLE
cannot run_alignment_tool 

### ISSUE THREAD

**Issue by nihar0602** [RobotLocomotion/LabelFusion#100]
Hi @peteflorence, when I'm trying to test the 5GB example set, I am seeing this error: 

```
root@587485a66cf4:~/labelfusion/data/data/logs/2017-06-15-73# run_alignment_tool 
Opening object alignment tool...
log folder: logs/2017-06-15-73
libGL error: No matching fbConfigs or visuals found
libGL error: failed to load driver: swrast
Traceback (most recent call last):
  File "/root/labelfusion/scripts/labelFusionApp.py", line 79, in <module>
    globalsDict=globals())
  File "/root/labelfusion/modules/labelfusion/setup.py", line 38, in setupLabelFusionDirector
    firstFrameToWorldTransform = utils.getFirstFrameToWorldTransform(filenames['transforms'])
TypeError: 'NoneType' object has no attribute '__getitem__'
Done.
```

Can anyone help me out understand what is the issue?

**Comment by nihar0602** [comment]
Closing this issue, as I figured it. 
To test it on nvidia-docker2, fork @ianchen-tw's repo. It is updated to last. 
Many thanks to @ianchen-tw  @patmarion @peteflorence  for making this possible.

**Comment by nihar0602** [comment]
Closing this issue, as I figured it. 
To test it on nvidia-docker2, fork @ianchen-tw's repo. It is updated to lastest. 
Many thanks to @ianchen-tw  @patmarion @peteflorence  for making this possible.
